name: frontend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  http: ^1.3.0
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  dropdown_button2: ^2.3.9
  darq: ^2.0.0
  collection: ^1.19.0
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: PokemonSolid
      fonts:
        - asset: assets/fonts/PokemonSolid.ttf

    - family: PokemonHollow
      fonts:
        - asset: assets/fonts/PokemonHollow.ttf

flutter_native_splash:
  color: "#000029"
  image: assets/images/splash_logo.png
  android_12:
    image: assets/images/splash_logo.png
    icon_background_color: "#000029"
